project:
  type: website
  output-dir: docs

website:
  title: "Nivedhitha Dhanasekaran"
  description: "Nive's Portfolio Website."
  site-url: "https://nive927.github.io/"
  
  repo-url: "https://github.com/nive927/nive927.github.io"
  
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
    # right:
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: resume.qmd
        text: Resume
      - href: cv.qmd
        text: CV
    search: true
    bread-crumbs: true

format:
  html:
    theme:
      - pulse # https://quarto.org/docs/output-formats/html-themes.html
      - custom.scss
      # dark: vapor
      # light: quartz
      
    css: styles.scss
    toc: true
    page-layout: full
    sidebar: false



