project:
  type: website
  output-dir: docs

website:
  title: "Nivedhitha Dhanasekaran"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      dark: vapor
      light: quartz
    css: styles.css
    toc: true
    page-layout: full
    sidebar: false



