---
title: "About"
---

I am Nivedhitha Dhanasekaran, a Master of Computational Data Science (MCDS) graduate student at the Language Technologies Institute of Carnegie Mellon University.

I was an undergraduate from 2018-2022 pursuing B.E. Computer Science and Engineering from Sri Sivasubramaniya Nadar College of Engineering, Chennai, India. While progressing through my undergraduate curriculum, I had the opportunity to work on projects in Full Stack Engineering, Data Science, and Deep Learning. In these projects, I participated in all the stages of the software development lifecycle, focusing on scalability, reliability, and user experience. I also have limited research experience in Computer Vision, Computational Biomedicine, and Robotics.

For the next year, I was a Technical Analyst at Citi, collaborating with the engineering and product teams to comprehend customer needs, implement technology solutions, and deliver exciting projects.

In my spare time, I enjoy exploring strategies, books, habits & tools that help me live a happier, healthier, and more productive life. A fun fact about me is that I'm a textbook INTJ-A personality type.
